version: '3'
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
    #    mem_limit: 500m
    #    cap_add:
    #      - IPC_LOCK
    #    volumes:
    #      - data01:/usr/share/elasticsearch/data

  db-postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    expose:
      - 5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq
    command: rabbitmq-server
    expose:
      - 5672
      - 15672

  discovery:
    image: microservice-docker-discovery-service:0.0.1-SNAPSHOT
    container_name: discovery
    ports:
      - 8761:8761

  proxy-service:
    image: microservice-docker-proxy-service:0.0.1-SNAPSHOT
    container_name: proxy-service
    environment:
      - EUREKA_SERVER=http://discovery:8761/eureka
      - JAVA_OPTS=
        -Dspring.profiles.active=prod
    depends_on:
      - discovery
    ports:
      - 8080:8080
    links:
      - discovery:discovery

  product-service:
    image: microservice-docker-product-service:0.0.1-SNAPSHOT
    environment:
      - EUREKA_SERVER=http://discovery:8761/eureka
      - JAVA_OPTS=
        -Dspring.profiles.active=prod
    depends_on:
      - discovery
      - rabbitmq
      - db-postgres
    links:
      - discovery:discovery
    expose:
      - 8081

  order-service:
    image: microservice-docker-order-service:0.0.1-SNAPSHOT
    container_name: order-service
    environment:
      - EUREKA_SERVER=http://discovery:8761/eureka
      - JAVA_OPTS=
        -Dspring.profiles.active=prod
    depends_on:
      - discovery
      - rabbitmq
      - db-postgres
    links:
      - discovery:discovery
    expose:
      - 8084

  event-service:
    image: microservice-docker-event-service:0.0.1-SNAPSHOT
    environment:
      - EUREKA_SERVER=http://discovery:8761/eureka
      - JAVA_OPTS=
        -Dspring.profiles.active=prod
    depends_on:
      - discovery
      - rabbitmq
      - db-postgres
    links:
      - discovery:discovery
    expose:
      - 8079

  user-service:
    image: microservice-docker-user-service:0.0.1-SNAPSHOT
    environment:
      - ELASTICSEARCH_IP=192.168.99.100:9200
      - EUREKA_SERVER=http://discovery:8761/eureka
      - JAVA_OPTS=
        -Dspring.profiles.active=prod
      - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
      - AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}
    depends_on:
      - discovery
      - elasticsearch
      - rabbitmq
    links:
      - discovery:discovery
    expose:
      - 8085

volumes:
  data01:
    driver: local
  pgdata:
